name: etl_pipeline_dbt_bq_airflow

profile: etl_pipeline_dbt_bq_airflow

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

# seeds:
  # run 'dbt seed' or dbt seed -s file_names_in_seeds_folder'
  # create a dataset name in BQ '<dataset name in BQ, set up in dbt/profiles.yml>_raw'
  # etl_pipeline_dbt_bq_airflow:
    # +schema: _raw # could remove this so files will be all saved in the same dataset i set up in dbt/profiles.yml

models:
  etl_pipeline_dbt_bq_airflow:
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: view
    marts:
      +materialized: table
